version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: databasepassword
      POSTGRES_DB: db_involved
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
