spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/db_involved
        username: postgresql
        password: PasswordDatabase
    flyway:
         baselineOnMigrate: true
         locations: classpath:db/migration
         enabled: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
        hibernate:
            ddl-auto: update

server:
    port: 8080
