spring:
    application:
        name: ms-content
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:ms-content
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: true
        defer-datasource-initialization: true
    h2:
        console:
            enable: true
        path: /h2-console

ms:
    involved:
        host: ${MS_INVOLVED_URL:http://localhost:8081}