spring:
    application:
        name: ms-content
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/db_conexao_respeito}
        username: ${DATABASE_USERNAME:postgresql}
        password:  ${BMS_DATABASE_PASSWORD:123456}
    flyway:
        baselineOnMigrate: true
        locations: classpath:db/migration
        enabled: true
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
        hibernate:
            ddl-auto: update

ms:
    involved:
        host: ${MS_INVOLVED_URL:http://localhost:8081}

server:
    port: 8080