create table tb_student (
        birth_date date,
        id_student bigint generated by default as identity,
        responsible_id bigint unique,
        address varchar(255),
        city varchar(255),
        cpf varchar(255) unique,
        educational_intitution varchar(255),
        email varchar(255),
        fullname varchar(255),
        name_responsible varchar(255),
        neighborhood varchar(255),
        password varchar(255),
        phone_number varchar(255),
        postal_code varchar(255),
        registration varchar(255) unique,
        primary key (id_student)
    )